GET http://localhost:3001/api/blogs/

###
GET http://localhost:3001/api/blogs/6076814b54814b05027651e5

###
DELETE http://localhost:3001/api/blogs/6076821d54814c05027651e8

###
PUT http://localhost:3001/api/blogs/6076814b54814c05027661e5
Content-Type: application/json

{
  "likes": 10
}


###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
  "author": "Prabhakar Rai"
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
  "url": "https://www.theprabhakar.in/2020/06/some.html"
}

###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
  "author": "Prabhakar Rai",
  "title": "Some other other blog by me",
  "url": "https://www.thepdfdar.in/2819/02/some.html"
}

###
GET http://localhost:3001/unknown_endpoint

###
GET http://localhost:3001/api/unknown_endpoint

###
GET http://localhost:3001/api/blogs/unknown_endpoint